Apply changes from 1.13.1-0ubuntu4

diff --git a/debian/tests/docker-in-lxd b/debian/tests/docker-in-lxd
--- a/debian/tests/docker-in-lxd
+++ b/debian/tests/docker-in-lxd
@@ -131,6 +131,18 @@ while ! lxc file pull docker/etc/resolv.conf - 2> /dev/null | grep -q ^nameserve
         exit 1
     fi
 done
+if ! lxc file pull docker/etc/resolv.conf - 2> /dev/null | grep ^nameserver | grep -qv 127.0.0.53
+then
+    echo "systemd-resolved"
+    while ! lxc file pull docker/run/systemd/resolve/resolv.conf - 2> /dev/null | grep -v fe80 | grep -q ^nameserver; do
+        sleep 1
+        attempts=$((attempts+1))
+        if [ $attempts -gt 30 ]; then
+            echo "Network failed to come up after 30 seconds"
+            exit 1
+        fi
+    done
+fi
 
 lxc exec docker -- apt-get update
 lxc exec docker -- apt-get install docker.io -y
