Use a debconf prompt to decide whether to restart the Docker daemon

diff --git a/debian/docker.io.postinst b/debian/docker.io.postinst
--- a/debian/docker.io.postinst
+++ b/debian/docker.io.postinst
@@ -1,6 +1,8 @@
 #!/bin/sh
 set -e
 
+. /usr/share/debconf/confmodule
+
 case "$1" in
 	configure)
 		if [ -z "$2" ]; then
@@ -24,4 +26,33 @@ case "$1" in
 		;;
 esac
 
+shouldStartRestart=
+if [ "$1" != 'reconfigure' ] && [ -z "${DEBCONF_RECONFIGURE:-}" ]; then
+	# (if we're just doing "dpkg-reconfigure", there's no reason to actually [re]start Docker)
+	shouldStartRestart=1
+fi
+
+# restart Docker if it's running (thus this is an upgrade) and the user (via debconf) told us they're OK with that
+db_version 2.0
+db_get docker.io/restart
+if \
+	[ "$RET" = 'true' ] \
+	&& [ -n "$2" ] && [ "$1" = 'configure' ] \
+	&& [ -n "$shouldStartRestart" ] \
+	&& [ -x /etc/init.d/docker ] \
+	&& invoke-rc.d --disclose-deny docker status > /dev/null 2>&1 \
+; then
+	# Docker daemon appears to be running and should be restarted
+	invoke-rc.d docker restart || :
+fi
+db_stop
+
 #DEBHELPER#
+
+# because we had to use "dh_installinit --no-start", we get to make sure the daemon is started on first install
+# (this is adapted from debhelper's "autoscripts/postinst-init")
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
+	if [ -x /etc/init.d/docker ] && [ -n "$shouldStartRestart" ] && ! invoke-rc.d docker status > /dev/null 2>&1 ; then
+		invoke-rc.d docker start || :
+	fi
+fi
