Reorganize the way we fetch/build our multi-orig tarballs for improved maintainability as the list grows

diff --git a/debian/helpers/download-libcontainer b/debian/helpers/download-libcontainer
--- a/debian/helpers/download-libcontainer
+++ b/debian/helpers/download-libcontainer
@@ -3,6 +3,13 @@ set -e
 
 mkdir -p "${DOCKER_TARBALLS:=../tarballs}"
 
+# MUST STAY IN SYNC WITH LIST IN "debian/rules"
+multiOrigGopkgs=(
+	github.com/docker/libcontainer
+	github.com/docker/libtrust
+	github.com/docker/distribution
+)
+
 pkg="$(dpkg-parsechangelog -SSource)"
 ver="$(dpkg-parsechangelog -SVersion)"
 origVer="${ver%-*}" # strip everything from the last dash
@@ -12,7 +19,7 @@ origTarballPrefix="${DOCKER_TARBALLS}/${pkg}_${origVer}.orig"
 unprunedTarballPrefix="${DOCKER_TARBALLS}/${pkg}_${upstreamVer}.orig"
 
 if command -v curl &> /dev/null; then
-	curl='curl -sSL'
+	curl='curl -fsSL'
 elif command -v wget &> /dev/null; then
 	curl='wget -qO-'
 else
@@ -36,29 +43,20 @@ get_hack_vendor() {
 	done
 }
 
-if libcontainerCommit="$(get_hack_vendor | grep -m1 '^clone git github.com/docker/libcontainer ' | cut -d' ' -f4)" && [ "$libcontainerCommit" ]; then
-	$curl "https://github.com/docker/libcontainer/archive/${libcontainerCommit}.tar.gz" > "${unprunedTarballPrefix}-libcontainer.tar.gz"
+ret=0
+for gopkg in "${multiOrigGopkgs[@]}"; do
+	commit="$(get_hack_vendor | awk '$1 == "clone" && $2 == "git" && $3 == "'"$gopkg"'" { print $4 }')"
+	if [ "$commit" ]; then
+		origTar="$unprunedTarballPrefix-$(basename "$gopkg").tar.gz"
+		$curl "https://$gopkg/archive/$commit.tar.gz" > "$origTar"
 
-	echo "successfully fetched ${unprunedTarballPrefix}-libcontainer.tar.gz"
-	echo "  (from libcontainer commit $libcontainerCommit)"
+		echo "successfully fetched $origTar"
+		echo "  (from $gopkg commit $commit)"
 
-	"$(dirname "$(readlink -f "$BASH_SOURCE")")/../repack.sh" --upstream-version "$upstreamVer" "${unprunedTarballPrefix}-libcontainer.tar.gz"
-fi
-
-if libtrustCommit="$(get_hack_vendor | grep -m1 '^clone git github.com/docker/libtrust ' | cut -d' ' -f4)" && [ "$libtrustCommit" ]; then
-	$curl "https://github.com/docker/libtrust/archive/${libtrustCommit}.tar.gz" > "${unprunedTarballPrefix}-libtrust.tar.gz"
-
-	echo "successfully fetched ${unprunedTarballPrefix}-libtrust.tar.gz"
-	echo "  (from libtrust commit $libtrustCommit)"
-
-	"$(dirname "$(readlink -f "$BASH_SOURCE")")/../repack.sh" --upstream-version "$upstreamVer" "${unprunedTarballPrefix}-libtrust.tar.gz"
-fi
-
-if distributionCommit="$(get_hack_vendor | grep -m1 '^clone git github.com/docker/distribution ' | cut -d' ' -f4)" && [ "$distributionCommit" ]; then
-	$curl "https://github.com/docker/distribution/archive/${distributionCommit}.tar.gz" > "${unprunedTarballPrefix}-distribution.tar.gz"
-
-	echo "successfully fetched ${unprunedTarballPrefix}-distribution.tar.gz"
-	echo "  (from distribution commit $distributionCommit)"
-
-	"$(dirname "$(readlink -f "$BASH_SOURCE")")/../repack.sh" --upstream-version "$upstreamVer" "${unprunedTarballPrefix}-distribution.tar.gz"
-fi
+		"$(dirname "$(readlink -f "$BASH_SOURCE")")/../repack.sh" --upstream-version "$upstreamVer" "$origTar"
+	else
+		echo >&2 "error: cannot find $gopkg commit!"
+		ret=1
+	fi
+done
+exit $ret
